import { Inter } from "next/font/google"
import Link from "next/link"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="navbar">
          <ul className="navbar-list">
            <li className="navbar-item">
              <Link href="/" className="navbar-link">
                Acasa
              </Link>
            </li>
            <li className="navbar-item">
              <Link href="/opere-artistice" className="navbar-link">
                Opere Artistice
              </Link>
            </li>
            <li className="navbar-item navbar-item-right">
              <Link href="/contact" className="navbar-link">
                Contact
              </Link>
            </li>
          </ul>
        </nav>

        {children}
      </body>
    </html>
  )
}
