export const paintings = [
  {
    id: 1,
    image: "/images/aurelia/expuse/1.jpg",
    title: "Trei frati",
    category: "original",
    description: "Tehnica: acrilic. Compoziție proprie",
    size: "mediu",
    price: 2000,
  },
  {
    id: 2,
    image: "/images/aurelia/expuse/2.jpg",
    title: "Dragoste",
    category: "reproducere",
    description:
      "Tehnica: acrilic. Reproducere după o compoziție accesibilă online. Autor interpretat",
    size: "mediu",
    price: 1500,
  },
  {
    id: 3,
    image: "/images/aurelia/expuse/3.jpg",
    title: "Balet si flori",
    category: "original",
    description: "Tehnica: acrilic. Compoziție proprie",
    size: "mediu",
    price: 2000,
  },
  {
    id: 4,
    image: "/images/aurelia/expuse/4.jpg",
    title: "Diversitate",
    category: "original",
    description: "Tehnica: acrilic. Compoziție proprie",
    size: "mediu",
    price: 2000,
  },
  {
    id: 5,
    image: "/images/aurelia/expuse/5.jpg",
    title: "Madame",
    category: "reproducere",
    description:
      "Tehnica: ulei. Reproducere după o compoziție accesibilă online. Autor interpretat",
    size: "mic",
    price: 1000,
  },
  {
    id: 6,
    image: "/images/aurelia/expuse/6.jpg",
    title: "Trepte spre Rai",
    category: "creatie",
    description:
      "Tehnica: ulei. Inspirat/interpretat după o compoziție accesibilă online. Tusa proprie",
    size: "mic",
    price: 800,
  },
  {
    id: 7,
    image: "/images/aurelia/expuse/7.jpg",
    title: "Femeia caleidoscop",
    category: "creatie",
    description:
      "Tehnica: acrilic. Inspirat/interpretat după o compoziție accesibilă online. Tusa proprie",
    size: "mic",
    price: 1000,
  },
  {
    id: 8,
    image: "/images/aurelia/expuse/8.jpg",
    title: "Monogamie",
    category: "creatie",
    description:
      "Tehnica: acrilic. Inspirat/interpretat după o compoziție accesibilă online. Tusa proprie",
    size: "mic-mediu",
    price: 800,
  },
  {
    id: 9,
    image: "/images/aurelia/expuse/9.jpg",
    title: "Menestreli",
    category: "reproducere",
    description:
      "Tehnica: ulei. Reproducere după o compoziție accesibilă online. Autor interpretat",
    size: "mic-mediu",
    price: 1000,
  },
  {
    id: 10,
    image: "/images/aurelia/expuse/10.jpg",
    title: "Senzatii...",
    category: "original",
    description: "Tehnica: acrilic. Compoziție proprie",
    size: "mediu",
    price: 1800,
  },
]
